# Generated by Django 3.1.2 on 2021-01-30 17:28

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, help_text='Image must be 200px by 200px.', null=True, validators=[users.models.validate_avatar], verbose_name='Date of Birth'),
        ),
    ]
