# Generated by Django 4.1.2 on 2022-11-15 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joke',
            old_name='modified',
            new_name='updated',
        ),
    ]
