# Generated by Django 4.1.2 on 2022-11-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0003_joke_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='slug',
            field=models.SlugField(default='boa', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
